// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbkemlelidocsoywezek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBia2VtbGVsaWRvY3NveXdlemVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDM3ODcsImV4cCI6MjA2Mzg3OTc4N30.IMgfmNMBMIDnydUTjByFooblD-u0_DtM-3oEVMWtIf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);